parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '9.6'
        schema_filter: '~^(?!(?:domain_messages|other_ignored_table))~'

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            PersonalInformation:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/PersonalInformation'
                prefix: 'App\PersonalInformation'
                alias: PersonalInformation
            PendingApplications:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/ApplicationProcess/PendingApplications'
                prefix: 'AcmeCompany\ApplicationProcess\PendingApplications'
                alias: PendingApplications
