parameters:
    locale: 'en'

services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    personal_information.repository:
        public: true
        class: App\PersonalInformation\DoctrinePersonalInformationRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'App\PersonalInformation\PersonalInformation'

    account.pending_applications:
        public: true
        class: AcmeCompany\ApplicationProcess\PendingApplications\DoctrinePendingApplicationRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'AcmeCompany\ApplicationProcess\PendingApplications\PendingApplication'

    account.pending_application_projection:
        class: AcmeCompany\ApplicationProcess\PendingApplications\PendingApplicationsProjection
        arguments:
            - '@account.pending_applications'
            - '@personal_information.repository'

    account.sending_emails.projection:
        class: AcmeCompany\ApplicationProcess\SendingEmailsDuringProcess\EmailSendingConsumer
        arguments:
            - '@mailer'
            - '@personal_information.repository'

    application.message_serializer:
        class: EventSauce\EventSourcing\Serialization\ConstructingMessageSerializer

    application.message_repository:
        class: EventSauce\DoctrineMessageRepository\DoctrineMessageRepository
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@application.message_serializer'
            - 'domain_messages'

    application.synchronous_message_dispatcher:
        class: EventSauce\EventSourcing\SynchronousMessageDispatcher
        arguments:
            - '@account.pending_application_projection'

    application.asynchronous_message_dispatcher:
        class: EventSauce\RabbitMQ\RabbitMQMessageDispatcher
        arguments:
            - '@old_sound_rabbit_mq.application_process_producer'
            - '@application.message_serializer'

    application.asynchronous_message_consumer:
        lazy: true
        class: EventSauce\RabbitMQ\RabbitMQConsumer
        arguments:
            - '@account.sending_emails.projection'
            - '@application.message_serializer'

    application.message_dispatcher:
        class: EventSauce\EventSourcing\MessageDispatcherChain
        arguments:
            - '@application.synchronous_message_dispatcher'
            - '@application.asynchronous_message_dispatcher'

    application.aggregate_root_repository:
        class: EventSauce\EventSourcing\ConstructingAggregateRootRepository
        arguments:
            - 'AcmeCompany\ApplicationProcess\Application'
            - '@application.message_repository'
            - '@application.message_dispatcher'

    application.command_handler:
        public: true
        class: AcmeCompany\ApplicationProcess\ApplicationCommandHandler
        arguments:
            - '@application.aggregate_root_repository'
            - '@personal_information.repository'

