<?php

namespace App\PersonalInformation;

use Doctrine\ORM\EntityRepository;
use Ramsey\Uuid\UuidInterface;

/**
 * PersonalInformationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DoctrinePersonalInformationRepository extends EntityRepository implements PersonalInformationRepository
{
    public function persist(PersonalInformation $personalInformation)
    {
        $em = $this->getEntityManager();
        $em->persist($personalInformation);
        $em->flush();
    }

    public function retrieve(UuidInterface $id): PersonalInformation
    {
        $personalInformation = $this->find($id);

        if ( ! $personalInformation instanceof PersonalInformation) {
            throw new PersonalInformationNotFound();
        }

        return $personalInformation;
    }
}
